export default [{
  type: 'CABIN',
  area: 'First',
  data: ['A','C','|','H', 'K'],
  bgColor: 'FFCCFF',
},{
    type: 'ROW',
    area: 991,
    data: ['O','','G','G'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 992,
    data: ['>','','','<'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 993,
    data: ['S','S','S','S'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 994,
    data: ['','M','M',''],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 1,
    data: ['ｽ','-','-','1'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 2,
    data: ['ｽ','-','-','1'],
    bgColor: '',
  },
  {
    type: 'CABIN',
    area: 'First',
    data: ['A','C','|','H', 'K'],
    bgColor: 'FFCCFF',
  },
  {
    type: 'CABIN',
    area: 'Economy',
    data: ['A','B','C','|','H','J','K'],
    bgColor: 'CCFFCC',
  },
  {
    type: 'ROW',
    area: 995,
    data: ['','M','','','M',''],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 5,
    data: ['R','P','P','_','_','ｾ'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 6,
    data: ['T','T','T','J','N','I'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 7,
    data: ['J','N','I','N','N','N'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 8,
    data: ['N','N','N','Z','Z','Z'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 9,
    data: ['Z','Z','Z','Z','Z','Z'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 10,
    data: ['ｸ','Z','B','B','Z','ｸ'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 11,
    data: ['ｸ','2','2','2','2','ｸ'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 12,
    data: ['2','2','2','2','2','2'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 13,
    data: ['.','.','.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 14,
    data: ['.','.','.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 15,
    data: ['.','.','.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 16,
    data: ['U','U','U','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 17,
    data: ['U','U','U','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 18,
    data: ['U','U','U','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 19,
    data: ['U','U','U','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 20,
    data: ['U','U','U','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 21,
    data: ['U','U','U','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 22,
    data: ['U','U','U','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 23,
    data: ['U','U','U','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 24,
    data: ['U','U','U','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 25,
    data: ['T','T','T','U','U','U'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 26,
    data: ['T','T','T','T','T','T'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 27,
    data: ['T','T','T','T','T','T'],
    bgColor: '',
  },
  {
    type: 'CABIN',
    area: 'Economy',
    data: ['A','B','C','|','H', 'J', 'K'],
    bgColor: 'CCFFCC',
  },
  {
    type: 'ROW',
    area: 996,
    data: ['S','S','','','S','S'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 997,
    data: ['O','','','','G','G'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 998,
    data: ['>','','','','','<'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 999,
    data: ['ｲ','','','','G','G'],
    bgColor: '',
  }
]