export default [{
  type: 'CABIN',
  area: 'Economy',
  data: ['A','B','|','C', 'D'],
  bgColor: 'CCFFCC',
},
{
    type: 'ROW',
    area: 997,
    data: ['','','','O'],
    bgColor: 'CCFFCC',
  },
  {
    type: 'ROW',
    area: 998,
    data: ['>','','',''],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 1,
    data: ['R','P','|','<'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 2,
    data: ['T','T','ｳ','ﾄ'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 3,
    data: ['T','T','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 4,
    data: ['T','T','T','T'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 5,
    data: ['T','T','T','T'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 6,
    data: ['T','T','T','T'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 7,
    data: ['T','T','T','T'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 8,
    data: ['.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 9,
    data: ['.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 10,
    data: ['.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 11,
    data: ['.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 12,
    data: ['.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 13,
    data: ['.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 14,
    data: ['.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 15,
    data: ['.','.','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 16,
    data: ['T','T','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 17,
    data: ['T','T','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 18,
    data: ['T','T','.','.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 19,
    data: ['T','T','.','.'],
    bgColor: '',
  },
  {
    type: 'CABIN',
    area: 'Economy',
    data: ['A','B','|','C', 'D'],
    bgColor: 'CCFFCC',
  },
  {
    type: 'ROW',
    area: 999,
    data: ['>','','','<'],
    bgColor: '',
  }
]