export default [{
  type: 'CABIN',
  area: 'First',
  data: ['A', 'C', '|', 'D', 'G', '|', 'H', 'K'],
  bgColor: 'FFCCFF',
},
  {
    type: 'ROW',
    area: 991,
    data: ['O', '', 'G', 'G', 'G', 'G'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 992,
    data: ['>', '', '?', 'C', '', '<'],
    bgColor: '',
  },
  {
    type: 'CABIN',
    area: 'First',
    data: ['A', 'C', '|', 'D', 'G', '|', 'H', 'K'],
    bgColor: 'FFCCFF',
  },
  {
    type: 'ROW',
    area: 993,
    data: ['M', '', 'M', '', 'M', ''],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 1,
    data: ['ｽ', '-', '-', '-', '-', '_'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 2,
    data: ['ｽ', '-', '-', '-', '-', 'ｾ'],
    bgColor: '',
  },
  {
    type: 'CABIN',
    area: 'First',
    data: ['A', 'C', '|', 'D', 'G', '|', 'H', 'K'],
    bgColor: 'FFCCFF',
  },
  {
    type: 'CABIN',
    area: 'Economy',
    data: ['A', 'B', 'C', '|', 'D', 'F', 'G', '|', 'H', 'J', 'K'],
    bgColor: 'CCFFCC',
  },
  {
    type: 'ROW',
    area: 994,
    data: ['', 'M', '', '', 'M', '', '', 'M', '', ''],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 5,
    data: ['ｽ', '-', '-', '-', 'ｾ', 'ｽ', '-', '-', 'ｾ'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 6,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 7,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 8,
    data: [')', '.', '.', '.', '.', '.', '.', '.', '('],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 9,
    data: ['|', 'C', '|', '.', '.', '.', '|', 'C', '|'],
    bgColor: '',
  },
  {
    type: 'CABIN',
    area: 'Economy',
    data: ['A', 'B', 'C', '|', 'D', 'F', 'G', '|', 'H', 'J', 'K'],
    bgColor: 'CCFFCC',
  },
  {
    type: 'ROW',
    area: 995,
    data: ['>', '', '', '', 'M', '', '', '', '<'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 10,
    data: ['ﾃ', 'ｳ', 'ｳ', '-', 'ｾ', 'ｽ', 'ｳ', 'ｳ', 'ﾄ'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 11,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 12,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 13,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 14,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 15,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 16,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 17,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 18,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 19,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 20,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 21,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 22,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 23,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 24,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 25,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 26,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 27,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 28,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 29,
    data: ['ｹ', '.', '.', '|', '|', '|', '.', '.', 'ｸ'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 996,
    data: ['', 'M', '', 'ｲ', 'ｲ', '', '', 'M', '', ''],
    bgColor: '',
  },
  {
    type: 'CABIN',
    area: 'Economy',
    data: ['A', 'B', 'C', '|', 'D', 'F', 'G', '|', 'H', 'J', 'K'],
    bgColor: 'CCFFCC',
  },
  {
    type: 'ROW',
    area: 997,
    data: ['>', '', '', '', 'M', '', '', '', '<'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 30,
    data: ['ﾃ', 'ｳ', 'ｳ', '-', '_', 'ｽ', 'ｳ', 'ｳ', 'ﾄ'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 31,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 32,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 33,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 34,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 35,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 36,
    data: ['.', '.', '.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 37,
    data: [')', '.', '.', '.', '.', '.', '.', '.', '('],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 38,
    data: ['ｽ', 'ｾ', '.', '.', '.', '.', '.', 'ｽ', 'ｾ'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 39,
    data: ['ｽ', 'ｾ', '.', '.', '.', '.', '.', 'ｽ', 'ｾ'],
    bgColor: '',
  },
  {
    type: 'CABIN',
    area: 'Economy',
    data: ['A', 'C', '|', 'D', 'F', 'G', '|', 'H', 'K'],
    bgColor: 'CCFFCC',
  },
  {
    type: 'ROW',
    area: 40,
    data: ['.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 41,
    data: ['.', '.', '.', '.', '.', '.', '.'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 42,
    data: ['>', '|', '.', '.', '.', '|', '<'],
    bgColor: '',
  },
  {
    type: 'CABIN',
    area: 'Economy',
    data: ['A', 'C', '|', 'D', 'F', 'G', '|', 'H', 'K'],
    bgColor: 'CCFFCC',
  },
  {
    type: 'ROW',
    area: 998,
    data: ['O', '', '', '', '', 'G', 'G'],
    bgColor: '',
  },
  {
    type: 'ROW',
    area: 999,
    data: ['', '', 'G', 'G', 'G', '', '', ''],
    bgColor: '',
  }
];

